# Generated by Django 5.1.6 on 2025-02-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('summary', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'news_articles',
                'ordering': ['-published_at'],
            },
        ),
    ]
