version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: superbowldocker
      POSTGRES_USER: jay
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "jay", "-d", "superbowldocker"]
      interval: 5s
      retries: 5
      start_period: 10s

  web:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy  # Ensure DB is ready before running web service
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "
      if [ ! -f /app/db_initialized ]; then
        python manage.py migrate && touch /app/db_initialized;
      fi;
      python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
